"""
Django settings for gym_system project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
import dj_database_url
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-r2l9yg^sr(e-_6j72t19jb^m!vgv-*w&mwthsgrhedbd#!e*i1'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'gestion',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware'
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'gym_system.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'gym_system.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# DEBE VERSE ASÍ:
# Configuración de Base de Datos Híbrida
DATABASES = {
    'default': dj_database_url.config(
        # Si estamos en la nube (Render), usa su base de datos
        default='postgresql://postgres:200Nicolas@localhost:5432/heimpel_db',
        conn_max_age=600
    )
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-cl'

TIME_ZONE = 'America/Santiago'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# --- CONFIGURACIÓN DE JAZZMIN (DISEÑO DEL ADMIN) ---

JAZZMIN_SETTINGS = {
    # Títulos
    "site_title": "Admin Heimpel",
    "site_header": "Heimpel Power Gym",
    "site_brand": "Heimpel Staff",
    "welcome_sign": "Panel de Control - Staff",
    "copyright": "Heimpel Power Gym Ltd",
    "search_model": ["gestion.Cliente"],

    # --- AQUÍ ESTÁ LA MAGIA: BOTONES SUPERIORES ---
    "topmenu_links": [
        # Botón 1: Ir al Home (Inicio) del Admin
        {"name": "Inicio Admin",  "url": "admin:index", "permissions": ["auth.view_user"]},

        # Botón 2: EL DASHBOARD FINANCIERO (Tu gráfico de ganancias)
        {"name": "💰 VER GANANCIAS", "url": "dashboard", "new_window": False},

        # Botón 3: Ver el sitio web como un cliente normal
        {"name": "Ver Sitio Web", "url": "home", "new_window": True},
    ],
    # ---------------------------------------------

    # Iconos del menú lateral
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        "gestion.Cliente": "fas fa-dumbbell",
        "gestion.Plan": "fas fa-list-alt",
        "gestion.Pago": "fas fa-money-bill-wave",
        "gestion.Membresia": "fas fa-id-card",
    },
    
    "show_ui_builder": False,
}
# TEMA OSCURO Y COLORES (Estilo Gym)
JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": "navbar-warning",  # Amarillo
    "accent": "accent-warning",        # Amarillo
    "navbar": "navbar-dark",
    "no_navbar_border": False,
    "navbar_fixed": False,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": True,
    "sidebar": "sidebar-dark-warning", # Barra lateral oscura con toques amarillos
    "sidebar_nav_small_text": False,
    "theme": "darkly",                 # TEMA OSCURO PROFESIONAL
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"
    }
}
ALLOWED_HOSTS = ['*']
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'